### ISSUE TITLE
Replace status with boolean error field

### ISSUE THREAD

**Issue by acdlite** [acdlite/flux-standard-action#6]
There's been a lot of confusion about `status` and its purpose. You can read some of the reasoning behind it here: https://github.com/acdlite/flux-standard-action/issues/4#issuecomment-118393978

I propose we replace `status` with a boolean `error` field. If `error` is true, then the action represents an error, and the payload should (by convention, like with rejected promises) be an error.

**Comment by clearjs** [comment]
Please describe what value would a restriction to a boolean provide?

**Comment by clearjs** [comment]
Disadvantages:

* not clear how to treat an absent field
* need an additional field for an error object
* makes it more difficult to be compliant

**Comment by acdlite** [comment]
@clearjs Any false-y value should be interpreted as success. Only `action.error === true` indicates failure.

**Comment by clearjs** [comment]
Good. Then why not go one step further, and allow any truthy value as well? For example, an error object.

**Comment by acdlite** [comment]
I would keep the error object in the payload. That way you don't get into a situation where an action has both a payload *and* an error object.

**Comment by clearjs** [comment]
@acdlite I think I've addressed that here: https://github.com/acdlite/flux-standard-action/issues/4#issuecomment-118398813

Also, your situation would work just fine with what I propose: `error === true` would still be truthy, so it would be FSA-compliant. But other usages (like an error in the error field) would be allowed as well without loss of functionality.

**Comment by clearjs** [comment]
By the way, sorry if my tone looks harsh or like I have hard feeling with respect to the outcome, both here and elsewhere. That isn't the intention at all. I'm being a little pedantic trying to clarify the motivation and making sure that most aspects have been considered.

**Comment by acdlite** [comment]
An action with `error === true`  is analogous to a rejected Promise. By convention, the payload should be an error object, but nothing's technically stopping you from breaking that convention. However, if you need to dispatch extra stuff, I would suggest catching the original error and dispatching a different action.

**Comment by acdlite** [comment]
@clearjs No problem, same goes for me! :)

**Comment by acdlite** [comment]
Changed in v0.6.0

**Comment by acdlite** [comment]
Please continue any discussion over here: https://github.com/acdlite/flux-standard-action/issues/7

**Comment by clearjs** [comment]
@acdlite looks like your last comment was intended for some other issue.

**Comment by acdlite** [comment]
Haha thanks!

**Comment by emmenko** [comment]
Just a minor note: if we're going with a boolean flag, woudn't be better `isError` or `hasError`?

**Comment by idolize** [comment]
I know this is an old issue, and it seems like the dust has already settled a bit, but I have a concern about errors in the FSA spec:

In the case of an error, the *entire* action `payload` is supposed to consist of a single `Error` object. Unfortunately, this restriction means that there is no way to add any additional payload information to the action. This can be problematic if there is other information required to handle the error, which I believe is a very likely scenario.

For example, if I am a developer and I have an `UPDATE_USER` action which requires a `userId` in the `payload`, my hypothetical Flux store (or reducer) probably needs that `userId` to update it's mapping of `userId -> user data`.

Likewise, if the `UPDATE_USER` action fails, and I dispatch an action with `error: true`, then I only get a single `Error` as my `payload`... **how does the store know which user failed to update**?

The only solutions currently allowed by the spec (that I can see) are adding the `userId` information to the `Error` (which I may not have control over) or adding it to `meta`, which seems wrong to me because this information is not really metadata at all, but rather a core piece of the action payload.

------

My proposed solution is to change the spec from:

> An action whose `error` is true is analogous to a rejected Promise. By convention, the `payload` SHOULD be an error object.

to something like the following:

> An action whose `error` is true is analogous to a rejected Promise. By convention, the `payload` SHOULD contain an error object inside an `error` field.

This is obviously a breaking change for code using the current spec; it would require error handling middleware to mirror the payload object with an additional `error` field:

**Ex:** ` dispatch({ ...prevAction, error: true, payload: { ...prevAction.payload, error: errorObj } })`).

And in addition, the handler of the action would have to access the error object via `action.payload.error` instead of `action.payload`.

However, the result would be much friendlier to Flux developers in my opinion.

**Comment by tappleby** [comment]
I dont see much value in having both `action.error` and `action.payload.error`. 

If we relaxed the `error` requirement to just contain a truthy value I think that be enough:

```js
dispatch({
	...prevAction
	error: {
		message: "Error saving user"
	}
});
```

**Comment by idolize** [comment]
@tappleby

Perfect. That idea also came to me before bed last night -- seems much simpler than requiring both, and it allows us to use the payload for other things :)

**Comment by tappleby** [comment]
I realized after posting that there was previous discussion about making `error` truthy, @acdlite gave some reasons for why error should be in `payload` but I think its worth revisiting.
