### ISSUE TITLE
GeoJSON conflicts with key `type`

### ISSUE THREAD

**Issue by gurre** [acdlite/flux-standard-action#71]
How do you manage a FSE which is a GeoJSON-object? Any suggestions? Putting the Geojson in it's own key?

**Comment by JaKXz** [comment]
Hi @gurre thanks for the question. I apologize for the slow reply, but I think the best place would be inside the `meta` key so that your action is FSA compliant.

If you wanted to be extra-organized, you could nest it in a `meta.geo` key or something to that effect so that you can have other properties in your `meta` as well, that isn't related to GeoJSON.

**Comment by gurre** [comment]
Thanks!
